# Generated by Django 4.0.4 on 2022-04-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Telegram User ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField(verbose_name='Size of bid')),
                ('result', models.BooleanField(verbose_name='Game result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Game datetime')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.profile', verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Game History',
                'verbose_name_plural': 'Game History',
            },
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(verbose_name='Number of coins')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.profile', verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Coins',
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
