# Generated by Django 3.2.13 on 2022-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_auto_20220424_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram User ID'),
        ),
    ]
