# Generated by Django 3.2.13 on 2022-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_alter_profile_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='Username'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('external_id', 'username'), name='unique_external_id_username'),
        ),
    ]
