# Generated by Django 3.2.13 on 2022-04-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0007_auto_20220424_1906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('external_id', 'username')},
        ),
    ]
