# Generated by Django 3.2.13 on 2022-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0008_alter_profile_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_external_id_username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=32, verbose_name='Username'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
