# Generated by Django 3.2.13 on 2022-04-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0010_alter_coins_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.profile', verbose_name='Username'),
        ),
    ]
