# Generated by Django 3.2.13 on 2022-05-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0011_alter_coins_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='bid',
            new_name='bet',
        ),
    ]
