# Generated by Django 4.0.4 on 2022-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0012_rename_bid_gamehistory_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='coins',
            field=models.BigIntegerField(verbose_name='Number of coins'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram User ID'),
        ),
    ]
